
name: main.yml
on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - uses: actions/checkout@v2
    - name: Copy NSSM & Ngrok to Windows Directory.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Connect your NGROK account
      run: .\ngrok.exe authtoken 2EmNVnloRc1WsaYg0dsPs0rNKAy_2GkPjtpS1AfE8heD9qpTw
    - name: Make YML file for NGROK.
      run: start NGROK-AP.bat
    - name: Create Tunnel
      run: .\ngrok.exe tcp --region ap 25565
    - name: Connect to your RDP 2core-7GB Ram.
